### ISSUE TITLE
Button in "Mein Unterricht" -> "Aktuelle Einträge" fälschlicherweise formatiert

### ISSUE THREAD

**Issue by gxalpha** [gxalpha/schulportal.css#5]
### Problembeschreibung
In "Mein Unterricht" -> "Aktuelle Einträge" wird die Höhe des "x offene Abgaben"-Knopfes fälschlicherweise verändert, von 32 auf 33 Pixel:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/59806498/106247695-2eda7680-6210-11eb-809a-ba30cb101767.png">

Ohne schulportal.css ist es korrekt:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/59806498/106247921-84af1e80-6210-11eb-8539-626aa4ddebe8.png">

### Weitere Informationen
Im Gegensatz zum "unerledigte Hausaufgaben"-Knopf, welcher ein `Button` ist, handelt es sich hier um ein `a`.
Es ist also gut möglich, dass wir irgendwo alle `a` formatieren, ohne es zu wollen.

**Comment by DrSquidyShity** [comment]
### Ergänzung
Ebenfalls falsche Buttonformatierung liegt auch bei "mein Unterricht" -> "Kursmappen" vor. Hier sind die offene Abgabe Buttons auch fälschlicherweise größer als die "unerleditgten HA".

Mit schulportal.css:
![image](https://user-images.githubusercontent.com/59874456/107144769-a5c4ed00-693d-11eb-85d2-f1de70a39338.png)

Ohne schulportal.css:
![image](https://user-images.githubusercontent.com/59874456/107144789-c55c1580-693d-11eb-8992-18bcb09a7b8d.png)

Hier liegt also ein ähnliches Problem wie oben vor.

Ps. Des Weiteren muss der "Unerledigte HA" Button auch hier rot gefärbt werden. und der "offene Abgaben" Button orange, um ein einheitliches Design zu gewährleisten.

**Comment by gxalpha** [comment]
Beide Fehler sollten behoben sein
